### PR TITLE
Homepage layout

### PR DESCRIPTION
**Pull request by cbgabe**

### CODE REVIEW

**Comment by mulysatest** [comment]
Do you got any demo site where I can see the how the latest version working?

**Comment by josemarluedke** [comment]
I don't think this PR was meant to be sent here. Closing it.

**Comment by cbgabe** [comment]
Sorry :D

**Comment by mpatrick** [comment]
Funny :smile:

**Comment by ssjr** [comment]
HAHAHAHAHAHAHAHAHA :joy:

**Pull request closed without merging**
